### PR TITLE
Update Polyline.encoded.js

### PR DESCRIPTION
**Pull request by PavlaQ**
Sometimes it tries call toFixed on undefined

### CODE REVIEW

**Comment by jieter** [comment]
Can you share a failing example and add a test?

**Comment by PavlaQ** [comment]
@jieter yeap, I changed condition for undefined values, and test was added

**Comment by jieter** [comment]
@PavlaQ Thanks for your contribution.

If I understand correctly from the unit tests, this is an issue while encoding lists of coordinates passed to the library. I'd say it is the responsibility of the calling code to ensure the points passed in the list are valid coordinates. In my opinion, Leaflet.encoded should not be made responsible for this. If we where to add a check like this we should also check for `NaN`, `Infinity`, etc.

This also violates the idea that `decode(encode(points)) == points` (or at least `decode(encode(points)).length == points.length`) as `decode` cannot restore the `[undefined, undefined]` in your example `[[38.5, -120.5], [40.7, -120.95], [43.252, -126.453], [undefined, undefined]];`.

**Comment by PavlaQ** [comment]
@jieter I agree that violates that idea but you shouldn't trust every input data. I dunno why list of waypoints from leaflet has any undefined values and where is bug. This situation is on single routes and it's not has any rule. 

I understand your worries about idea decode() - encode() etc but situation when method return error and it's crashed is not good

**Comment by PavlaQ** [comment]
IMHO situation when your not accept shitty data is better as when library return unexpected error

**Comment by PavlaQ** [comment]
@jieter will you merge this PR?

**Comment by PavlaQ** [comment]
@jieter  will you merge this PR? and publish on npm?

**Comment by jieter** [comment]
@PavlaQ please consider I'm voluntarily maintaining Leaflet.encoded; I'm not always able to devote time to it. Repeatedly asking for progress does not really help.

I still think supplying a valid list of points is the responsibility of the caller. If this library where to add a check, I think we should not try to correct it but fail with a clear error message. Something like turfjs does:

```JavaScript
var polygon = turf.polygon([[[-81, 41], [-88, 36], [-84, 31], [-80, 33], [-77, undefined], [-81, 41]]]);
turf.centroid(polygon);
```

```
Uncaught Error: coordinates must contain numbers
    at a (turf.min.js:1:1705)
    at Object.En [as centroid] (turf.min.js:43:44256)
    at <anonymous>:3:6
```

**Pull request closed without merging**
